#version: '3.0'  # docker compose第二版中version已经过时
services:
  etcd:
    image: 'bitnami/etcd:3.5.9'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      #      所以你要用 12379 端口来连接 etcd
      - '12379:2379'
